runtime: java17  # o la versión de Java que uses
instance_class: F2  # Tipo de instancia

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  # Variables de entorno para la base de datos
  SPRING_DATASOURCE_URL: "jdbc:postgresql://34.72.86.112:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "josujovasgg"

handlers:
  - url: /.*
    script: auto
    secure: always  # Fuerza HTTPS

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

network:
  instance_tag: spring-boot-app
  forwarded_ports:
    - 9090  # Puerto que usas en tu aplicación