spring:
  datasource:
    url: jdbc:postgresql://34.72.86.112:5432/postgres
    username: postgres
    password: josujovasgg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # Añadido dialect explícitamente
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Optimización añadida
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false
      max-age: 3600
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true # Añadido para evitar problemas con beans
    allow-circular-references: true # Añadido para manejar dependencias circulares

# Configuración de logging para debug
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.alibou.security: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 9090
  forward-headers-strategy: native
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    threads:
      max: 200
      min-spare: 10
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false
      max-age: 3600

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000